#!/usr/bin/env python3
import os
import sys
import subprocess

def main():
    script_dir = os.path.dirname(os.path.realpath(__file__))
    launch_script = os.path.join(script_dir, '..', 'launch_slicer.sh')
    slicer_code = "tests = slicer.util.getModuleLogic('ROS2Tests'); tests.run()"

    cmd = [
        launch_script,
        "--testing",
        "--python-code", slicer_code,
    ]

    try:
        res = subprocess.run(cmd)
        sys.exit(res.returncode)
    except KeyboardInterrupt:
        sys.exit(1)

if __name__ == '__main__':
    main()
